Adds a limit to download attempts.

diff --git a/scripts/lib/helper_functions b/scripts/lib/helper_functions
--- a/scripts/lib/helper_functions
+++ b/scripts/lib/helper_functions
@@ -35,8 +35,15 @@ function smart_download() {
     if [[ -f $PATH_LOCAL_FILE ]]; then
         echo "File $PATH_LOCAL_FILE exists. Determining point to resume download from."
     fi
+    attempts=1
     until curl -C - -L -u "${ARTIFACTORY_USER}:${ARTIFACTORY_TOKEN}" -o $PATH_LOCAL_FILE $DOWNLOAD_URL
     do
+        ((attempts+=1))
+        echo "DW - $attempts"
+        if [[ $attempts -gt "14" ]]; then
+            echo "Failed 15 times. Aborting download..."
+            exit 1
+        fi
         echo "Resuming download..."
         sleep 1
     done
